apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-consumer-api-deployment
  annotations:
    autor: Marcelo Cedro
spec:
  replicas: 1  # Número de réplicas (pods) da aplicação
  selector:
    matchLabels:
      app: identity-consumer-api
  template:
    metadata:
      labels:
        app: identity-consumer-api
    spec:
      containers:
      - name: identity-consumer-api
        image: rmahlow/fiaphackatoonidentityconsumerapi:3.0  # Imagem Docker da sua API
        ports:
        - containerPort: 8082  # Porta exposta dentro do container
        resources:
          limits:
            cpu: "0.5"        # Limite máximo de CPU
            memory: 512Mi   # Limite máximo de memória
          requests:
            cpu: "0.2"        # Recurso mínimo reservado de CPU
            memory: 256Mi   # Recurso mínimo reservado de memória

        # Variáveis de ambiente injetadas via Secret
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: identity-api-consumer-secrets
              key: DefaultConnection
        - name: SecretJWT
          valueFrom:
            secretKeyRef:
              name: identity-api-consumer-secrets
              key: SecretJWT
        - name: MassTransit__UserName
          valueFrom:
            secretKeyRef:
              name: identity-api-consumer-secrets
              key: User
        - name: MassTransit__Password
          valueFrom:
            secretKeyRef:
              name: identity-api-consumer-secrets
              key: Password              
        - name: MassTransit__Server
          valueFrom:
            configMapKeyRef: 
              name: identity-consumer-configmap
              key: "Server"
        - name: MassTransit__Port
          valueFrom:
            configMapKeyRef: 
              name: identity-consumer-configmap
              key: "Port"                              
        - name: MassTransit__QueueNameClienteCreate
          valueFrom:
            configMapKeyRef: 
              name: identity-consumer-configmap
              key: "QueueNameClienteCreate"   
        - name: MassTransit__QueueNameClienteUpdate
          valueFrom:
            configMapKeyRef: 
              name: identity-consumer-configmap
              key: "QueueNameClienteUpdate"   
        - name: MassTransit__QueueNameEmployeeCreate
          valueFrom:
            configMapKeyRef: 
              name: identity-consumer-configmap
              key: "QueueNameEmployeeCreate"   
        - name: MassTransit__QueueNameEmployeeUpdate
          valueFrom:
            configMapKeyRef: 
              name: identity-consumer-configmap
              key: "QueueNameEmployeeUpdate"   

        # 🩺 Liveness Probe: Verifica se o container ainda está saudável
        # Se falhar consecutivamente, o pod será reiniciado
        # livenessProbe:
        #   httpGet:
        #     path: /health  # Endpoint da sua API que indica saúde
        #     port: 8020     # Porta onde o serviço está ouvindo
        #   initialDelaySeconds: 15  # Tempo inicial de espera antes de iniciar o primeiro check
        #   periodSeconds: 10        # Frequência com que o check será feito
        #   failureThreshold: 3      # Número de falhas consecutivas antes de reiniciar o pod